---
title: "My Fisheries Analysis"
author: "Herb"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(paletteer)
```

Read data
```{r}
us_landings <- read_csv(here("data", "noaa_landings.csv"),
                        na = "no data")
```

clean col names
```{r}
salmon_clean <- us_landings %>% 
  clean_names() %>% 
  mutate(afs_name = str_to_lower(afs_name)) %>% 
  mutate(dollars_num = parse_number(dollars_usd)) %>% 
  filter(str_detect(afs_name, "salmon")) %>% 
  separate(afs_name, c("salmon_group", "subgroup"), sep = ", ") %>% 
  drop_na(dollars_num)
```

### Get annual total value by Salmon subgroup

```{r}
salmon_us_annual <- salmon_clean %>% 
  group_by(year, subgroup) %>% 
  summarise(tot_value = sum(dollars_num))
```

### line graph by subgroup
```{r}
salmon_us_annual %>% ggplot(aes(year, tot_value, color = subgroup)) +
  geom_line() +
  theme_bw() +
  labs(x = "Year", y = "US commercial salmon value (USD",
       title = "USinstall.packages Salmon Graph")+
  scale_color_paletteer_d("calecopal::figmtn")
  # calecopal	figmtn
# fishualize	Balistapus_undulatus
```

